### ISSUE TITLE
UTF8 and JSON are undefined

### ISSUE THREAD

**Issue by viratshukla** [mjohnsullivan/nomnom#6]
Even after running packages get and packages upgrade, I am getting UTF8 and JSON are undefined in places_2.dart file.
![image](https://user-images.githubusercontent.com/11851800/44443775-1d302600-a5f7-11e8-82f4-8db4406f6a8a.png)

**Comment by viratshukla** [comment]
I used json instead of JSON. error was removed. But I am still getting error for UTF8.
Please help me fix it.

**Comment by viratshukla** [comment]
Please help me fix it. Currently I am using IntelliJ Idea community edition 2018.2 latest edition at this time.

**Comment by viratshukla** [comment]
working, just put them in lower case. Its working now

**Comment by ravinakalkani** [comment]
ohh thank you :)
